### POST - save lists
POST http://localhost:8080/ HTTP/1.1
Content-Type: application/json

{
  "newChanges": {
    "lists": [
      {
        "title": "test title",
        "cards": [
          {
            "content": "test content1"
          }
        ]
      }
    ]
  }
}

### POST - detect any changes
POST http://localhost:8080/detect HTTP/1.1
Content-Type: application/json

{
  "newChanges": {
    "lists": [
      {
        "title": "test title",
        "cards": [
          {
            "content": "test 2"
          }
        ]
      }
    ]
  }
}

### GET - load lists
GET http://localhost:8080/ HTTP/1.1
Content-Type: application/json
